import { Fixtures } from '../../interfaces'

const fixtures: Fixtures = {
  pr_allergens: [
    {
      id_allergen: 'eggs',
      description: 'somebody can be allergic to eggs',
      __STATE__: 'PUBLIC',
    },
    {
      id_allergen: 'fish',
      description: 'somebody can be allergic to fish',
      __STATE__: 'PUBLIC',
    },
    {
      id_allergen: 'nuts',
      description: 'somebody can be allergic to nuts',
      __STATE__: 'PUBLIC',
    },
    {
      id_allergen: 'gluten',
      description: 'somebody can be allergic to gluten',
      __STATE__: 'PUBLIC',
    },
  ],
  pr_allergens_registry: [
    {
      ID_ALLERGEN: 'eggs',
      ID_USER: 'user001',
      COMMENTS: 'user001 is allergic to eggs',
      __STATE__: 'PUBLIC',
    },
    {
      ID_ALLERGEN: 'gluten',
      ID_USER: 'user002',
      COMMENTS: 'user002 is allergic to gluten',
      __STATE__: 'PUBLIC',
    },
    {
      ID_ALLERGEN: 'fish',
      ID_USER: 'user003',
      COMMENTS: 'user003 is allergic to fish',
      __STATE__: 'PUBLIC',
    },
    {
      ID_ALLERGEN: 'nuts',
      ID_USER: 'user004',
      COMMENTS: 'user004 is allergic to nuts',
      __STATE__: 'PUBLIC',
    },
    {
      ID_ALLERGEN: 'nuts',
      ID_USER: 'user005',
      COMMENTS: 'user005 is allergic to nuts',
      __STATE__: 'PUBLIC',
    },
  ],
  pr_dishes: [
    {
      id_dish: 'amatriciana',
      id_restaurant: 'pastaefagioli',
      price: 9,
      description: 'Amatriciana di Pasta e Fagioli',
      __STATE__: 'PUBLIC',
    },
    {
      id_dish: 'cotoletta',
      id_restaurant: 'pastaefagioli',
      price: 12,
      description: 'Cotoletta di Pasta e Fagioli',
      __STATE__: 'PUBLIC',
    },
    {
      id_dish: 'pastasugopolpette',
      id_restaurant: 'tavernadeiterroni',
      price: 7,
      description: 'Pasta con sugo di pomodoro e polpette di carne di Taverna dei Terroni',
      __STATE__: 'PUBLIC',
    },
    {
      id_dish: 'frico',
      id_restaurant: 'osteriadellastazione',
      price: 15,
      description: 'Frico di Osteria della stazione',
      __STATE__: 'PUBLIC',
    },
    {
      id_dish: 'mezzofrico',
      id_restaurant: 'osteriadellastazione',
      price: 8,
      description: 'Mezza porzione di frico di Osteria della stazione',
      __STATE__: 'TRASH',
    },
  ],
  pr_orders: [
    {
      ID_ORDER: 'order001',
      ID_USER: 'user001',
      DATE: '2007-12-03T02:55:44.000Z',
      TOTAL_PRICE: '21',
      ORDER_STATUS: 'In shipping',
      PAYMENT_TYPE: 'Cash',
      __STATE__: 'PUBLIC',
    },
    {
      ID_ORDER: 'order002',
      ID_USER: 'user004',
      DATE: '2018-01-04T02:43:44.000Z',
      TOTAL_PRICE: '7',
      ORDER_STATUS: 'Completed',
      PAYMENT_TYPE: 'Credit Card',
      __STATE__: 'PUBLIC',
    },
    {
      ID_ORDER: 'order003',
      ID_USER: 'user005',
      DATE: '2018-01-04T02:43:44.000Z',
      TOTAL_PRICE: '15',
      ORDER_STATUS: 'Completed',
      PAYMENT_TYPE: 'Credit Card',
      __STATE__: 'PUBLIC',
    },
  ],
  pr_orders_dishes: [
    {
      ID_ORDER: 'order001',
      ID_DISH: 'amatriciana',
      __STATE__: 'PUBLIC',
    },
    {
      ID_ORDER: 'order001',
      ID_DISH: 'cotoletta',
      __STATE__: 'PUBLIC',
    },
    {
      ID_ORDER: 'order002',
      ID_DISH: 'pastasugopolpette',
      __STATE__: 'PUBLIC',
    },
    {
      ID_ORDER: '003',
      ID_DISH: 'frico',
      __STATE__: 'PUBLIC',
    },
  ],
  pr_registry: [
    {
      ID_USER: 'user001',
      NAME: 'Nick',
      SURNAME: 'Jackson',
      GENDER: 'Male',
      TAX_CODE: 'nick_jackson_tax_code',
      EMAIL: 'nick_jackson@mail.com',
      ADDRESS: 'nick_jackson_address',
      PHONE: 'nick_jackson_phone_number',
      PROFESSION: 'nick_jackson_profession',
      __STATE__: 'PUBLIC',
    },
    {
      ID_USER: 'user002',
      NAME: 'Dante',
      SURNAME: 'Martin',
      GENDER: 'Male',
      EMAIL: 'dante_martin@mail.com',
      TAX_CODE: 'dante_martin_tax_code',
      ADDRESS: 'dante_martin_address',
      PHONE: 'dante_martin_phone_number',
      PROFESSION: 'dante_martin_profession',
      __STATE__: 'PUBLIC',
    },
    {
      ID_USER: 'user003',
      NAME: 'Stokely',
      SURNAME: 'Hathaway',
      GENDER: 'Male',
      EMAIL: 'stokely_hathaway@mail.com',
      TAX_CODE: 'stokely_hathaway_tax_code',
      ADDRESS: 'stokely_hathaway_address',
      PHONE: 'stokely_hathaway_phone_number',
      PROFESSION: 'stokely_hathaway_profession',
      __STATE__: 'PUBLIC',
    },
    {
      ID_USER: 'user004',
      NAME: 'Jamie',
      SURNAME: 'Hayter',
      GENDER: 'Female',
      EMAIL: 'jamie_hayter@mail.com',
      TAX_CODE: 'jamie_hayter_tax_code',
      ADDRESS: 'jamie_hayter_address',
      PHONE: 'jamie_hayter_phone_number',
      PROFESSION: 'jamie_hayter_profession',
      __STATE__: 'PUBLIC',
    },
    {
      ID_USER: 'user005',
      NAME: 'Kris',
      SURNAME: 'Statlander',
      GENDER: 'Female',
      EMAIL: 'kris_statlander@mail.com',
      TAX_CODE: 'kris_statlander_tax_code',
      ADDRESS: 'kris_statlander_address',
      PHONE: 'kris_statlander_phone_number',
      PROFESSION: 'kris_statlander_profession',
      __STATE__: 'PUBLIC',
    },
  ],
  pr_restaurants: [
    {
      id_restaurant: 'pastaefagioli',
      name: 'Pasta e Fagioli',
      __STATE__: 'PUBLIC',
    },
    {
      id_restaurant: 'tavernadeiterroni',
      name: 'Taverna dei Terroni',
      __STATE__: 'PUBLIC',
    },
    {
      id_restaurant: 'osteriadellastazione',
      name: 'Osteria della Stazione',
      __STATE__: 'PUBLIC',
    },
  ],
  pr_reviews: [
    {
      ID_REVIEW: 'review001',
      ID_USER: 'user001',
      ID_DISH: 'amatriciana',
      TEXT: 'Spectacular!',
      STARS: 5,
      __STATE__: 'PUBLIC',
    },
    {
      ID_REVIEW: 'review002',
      ID_USER: 'user001',
      ID_DISH: 'cotoletta',
      TEXT: 'Good enough!',
      STARS: 4,
      __STATE__: 'PUBLIC',
    },
    {
      ID_REVIEW: 'review003',
      ID_USER: 'user003',
      ID_DISH: 'pastasugopolpette',
      TEXT: 'Pretty bad...',
      STARS: 2,
      __STATE__: 'PUBLIC',
    },
    {
      ID_REVIEW: 'review004',
      ID_USER: 'user005',
      ID_DISH: 'frico',
      TEXT: 'Almost perfect',
      STARS: 4,
      __STATE__: 'PUBLIC',
    },
    {
      ID_REVIEW: 'review005',
      ID_USER: 'user005',
      ID_DISH: 'amatriciana',
      TEXT: 'Ok!',
      STARS: 3,
      __STATE__: 'PUBLIC',
    },
    {
      ID_REVIEW: 'review006',
      ID_USER: 'user005',
      ID_DISH: 'cotoletta',
      TEXT: 'Good!',
      STARS: 3,
      __STATE__: 'PUBLIC',
    },
    {
      ID_REVIEW: 'review007',
      ID_USER: 'user002',
      ID_DISH: 'pastasugopolpette',
      TEXT: 'Good enough',
      STARS: 4,
      __STATE__: 'PUBLIC',
    },
    {
      ID_REVIEW: 'review008',
      ID_USER: 'user002',
      ID_DISH: 'frico',
      TEXT: 'Ok',
      STARS: 3,
      __STATE__: 'PUBLIC',
    },
  ],
  pr_food_preferencies: [
    {
      ID_FOOD_PREFERENCE: 'bacon',
      DESCRIPTION: 'bacon is food generally liked',
      __STATE__: 'PUBLIC',
    },
    {
      ID_FOOD_PREFERENCE: 'chips',
      DESCRIPTION: 'chips is food generally liked',
      __STATE__: 'DRAFT',
    },
    {
      ID_FOOD_PREFERENCE: 'fish',
      DESCRIPTION: 'fish is food generally liked',
      __STATE__: 'PUBLIC',
    },
  ],
  pr_food_preferencies_registry: [
    {
      ID_FOOD_PREFERENCE: 'bacon',
      ID_USER: 'user001',
      COMMENTS: 'user001 likes bacon',
      __STATE__: 'PUBLIC',
    },
    {
      ID_FOOD_PREFERENCE: 'chips',
      ID_USER: 'user001',
      COMMENTS: 'user001 likes chips',
      __STATE__: 'PUBLIC',
    },
    {
      ID_FOOD_PREFERENCE: 'fish',
      ID_USER: 'user003',
      COMMENTS: 'user003 likes fish',
      __STATE__: 'PUBLIC',
    },
  ],
}

export default fixtures
